// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	AuthenticateRequest
	AuthenticateReply
	TransportContext
	ProtocolContext
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthenticateRequest struct {
	Protocol  *ProtocolContext  `protobuf:"bytes,1,opt,name=protocol" json:"protocol,omitempty"`
	Transport *TransportContext `protobuf:"bytes,2,opt,name=transport" json:"transport,omitempty"`
}

func (m *AuthenticateRequest) Reset()                    { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()               {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthenticateRequest) GetProtocol() *ProtocolContext {
	if m != nil {
		return m.Protocol
	}
	return nil
}

func (m *AuthenticateRequest) GetTransport() *TransportContext {
	if m != nil {
		return m.Transport
	}
	return nil
}

type AuthenticateReply struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Tenant  string `protobuf:"bytes,2,opt,name=tenant" json:"tenant,omitempty"`
}

func (m *AuthenticateReply) Reset()                    { *m = AuthenticateReply{} }
func (m *AuthenticateReply) String() string            { return proto.CompactTextString(m) }
func (*AuthenticateReply) ProtoMessage()               {}
func (*AuthenticateReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthenticateReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AuthenticateReply) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type TransportContext struct {
	Encrypted       bool   `protobuf:"varint,1,opt,name=encrypted" json:"encrypted,omitempty"`
	RemoteAddress   string `protobuf:"bytes,2,opt,name=remoteAddress" json:"remoteAddress,omitempty"`
	X509Certificate []byte `protobuf:"bytes,3,opt,name=x509Certificate,proto3" json:"x509Certificate,omitempty"`
}

func (m *TransportContext) Reset()                    { *m = TransportContext{} }
func (m *TransportContext) String() string            { return proto.CompactTextString(m) }
func (*TransportContext) ProtoMessage()               {}
func (*TransportContext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TransportContext) GetEncrypted() bool {
	if m != nil {
		return m.Encrypted
	}
	return false
}

func (m *TransportContext) GetRemoteAddress() string {
	if m != nil {
		return m.RemoteAddress
	}
	return ""
}

func (m *TransportContext) GetX509Certificate() []byte {
	if m != nil {
		return m.X509Certificate
	}
	return nil
}

type ProtocolContext struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *ProtocolContext) Reset()                    { *m = ProtocolContext{} }
func (m *ProtocolContext) String() string            { return proto.CompactTextString(m) }
func (*ProtocolContext) ProtoMessage()               {}
func (*ProtocolContext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ProtocolContext) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ProtocolContext) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthenticateRequest)(nil), "AuthenticateRequest")
	proto.RegisterType((*AuthenticateReply)(nil), "AuthenticateReply")
	proto.RegisterType((*TransportContext)(nil), "TransportContext")
	proto.RegisterType((*ProtocolContext)(nil), "ProtocolContext")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuthenticationService service

type AuthenticationServiceClient interface {
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateReply, error)
}

type authenticationServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthenticationServiceClient(cc *grpc.ClientConn) AuthenticationServiceClient {
	return &authenticationServiceClient{cc}
}

func (c *authenticationServiceClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateReply, error) {
	out := new(AuthenticateReply)
	err := grpc.Invoke(ctx, "/AuthenticationService/Authenticate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthenticationService service

type AuthenticationServiceServer interface {
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateReply, error)
}

func RegisterAuthenticationServiceServer(s *grpc.Server, srv AuthenticationServiceServer) {
	s.RegisterService(&_AuthenticationService_serviceDesc, srv)
}

func _AuthenticationService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthenticationService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthenticationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AuthenticationService",
	HandlerType: (*AuthenticationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _AuthenticationService_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types.proto",
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x14, 0xc4, 0x89, 0x42, 0x4d, 0x5e, 0x2b, 0x6d, 0xd7, 0x3f, 0x84, 0xe2, 0xa1, 0x04, 0x0f, 0x39,
	0x48, 0x94, 0x8a, 0xa0, 0xc7, 0x52, 0x3c, 0x78, 0xd3, 0xd5, 0x2f, 0x10, 0x37, 0x4f, 0x0c, 0xb4,
	0xbb, 0xeb, 0xee, 0x8b, 0x36, 0x37, 0x3f, 0xba, 0x74, 0x9b, 0xa4, 0x6d, 0xec, 0x71, 0x66, 0x87,
	0xf9, 0x2d, 0xf3, 0xa0, 0x4b, 0xa5, 0x46, 0x9b, 0x68, 0xa3, 0x48, 0x45, 0x04, 0x27, 0xd3, 0x82,
	0x3e, 0x51, 0x52, 0x2e, 0x52, 0x42, 0x8e, 0x5f, 0x05, 0x5a, 0x62, 0x57, 0xe0, 0xbb, 0x77, 0xa1,
	0xe6, 0xa1, 0x37, 0xf6, 0xe2, 0xee, 0x64, 0x90, 0x3c, 0x57, 0xc6, 0x4c, 0x49, 0xc2, 0x25, 0xf1,
	0x26, 0xc1, 0xae, 0x21, 0x20, 0x93, 0x4a, 0xab, 0x95, 0xa1, 0xf0, 0xc0, 0xc5, 0x87, 0xc9, 0x5b,
	0xed, 0xd4, 0xf9, 0x4d, 0x26, 0x7a, 0x84, 0xe1, 0x2e, 0x55, 0xcf, 0x4b, 0x16, 0xc2, 0x91, 0x2d,
	0x84, 0x40, 0x6b, 0x1d, 0xd2, 0xe7, 0xb5, 0x64, 0xe7, 0xd0, 0x21, 0x94, 0xa9, 0x5c, 0x97, 0x07,
	0xbc, 0x52, 0xd1, 0xaf, 0x07, 0x83, 0x36, 0x86, 0x5d, 0x40, 0x80, 0x52, 0x98, 0x52, 0x13, 0x66,
	0x55, 0xd1, 0xc6, 0x60, 0x97, 0x70, 0x6c, 0x70, 0xa1, 0x08, 0xa7, 0x59, 0x66, 0x56, 0xa8, 0x75,
	0xe3, 0xae, 0xc9, 0x62, 0xe8, 0x2f, 0xef, 0x6e, 0x1e, 0x66, 0x68, 0x28, 0xff, 0x70, 0x5f, 0x0c,
	0x0f, 0xc7, 0x5e, 0xdc, 0xe3, 0x6d, 0x3b, 0x7a, 0x82, 0x7e, 0x6b, 0x17, 0x36, 0x02, 0xbf, 0xb0,
	0x68, 0x64, 0xba, 0x40, 0xc7, 0x0f, 0x78, 0xa3, 0x57, 0x6f, 0x3a, 0xb5, 0xf6, 0x47, 0x99, 0xac,
	0x22, 0x37, 0x7a, 0xf2, 0x02, 0x67, 0x5b, 0xa3, 0xe4, 0x4a, 0xbe, 0xa2, 0xf9, 0xce, 0x05, 0xb2,
	0x7b, 0xe8, 0x6d, 0xaf, 0xc5, 0x4e, 0x93, 0x3d, 0x27, 0x1b, 0xb1, 0xe4, 0xdf, 0xa4, 0xef, 0x1d,
	0x77, 0xa2, 0xdb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x86, 0xe4, 0x85, 0xf3, 0x01, 0x00,
	0x00,
}
